# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bookmark < Formula
  desc "CLI tool for searching and opening bookmarks"
  homepage "https://github.com/martensjostrand/bookmark"
  version "0.2.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/martensjostrand/bookmark/releases/download/v0.2.1/bookmark_0.2.1_darwin_amd64.tar.gz"
    sha256 "9c06277cba33bcbc6b71e6ac864e43fea8e5b4dbfbc38d38dcd85648fc05ecc8"

    define_method(:install) do
      bin.install "bm"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/martensjostrand/bookmark/releases/download/v0.2.1/bookmark_0.2.1_darwin_arm64.tar.gz"
    sha256 "94209240577a3720434abf041fba19e14d688ff96bcdbe430a0b89346b2a5b7d"

    define_method(:install) do
      bin.install "bm"
    end
  end
end
